CREATE TABLE DEPT_TCL 
    AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TCL;

-- 11-3 rollback
INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');
ROLLBACK;
SELECT * FROM DEPT_TCL;

-- 11-4 commit
INSERT INTO DEPT_TCL VALUES(50, 'NETWORK', 'SEOUL');
COMMIT;
SELECT * FROM DEPT_TCL;
ROLLBACK;
SELECT * FROM DEPT_TCL;
 