-- 13-14 sys 계정으로 뷰 생성 권한 부여
grant create view to testuser;

-- 13-15 뷰 생성하기
CREATE VIEW VW_EMP20
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO = 20);

-- 13-16 생성한 뷰 확인하기
SELECT * FROM USER_VIEWS;

-- 13-17 생성한 뷰 조회하기
SELECT * FROM VW_EMP20;

-- 13-18 뷰 삭제
DROP VIEW VW_EMP20;

-- 13-26 sys 계정으로 시퀀스 생성 권한 부여
GRANT CREATE SEQUENCE TO testuser;

-- 13-27 dept 테이블을 사용하여 시퀀스 테이블 생성
CREATE TABLE DEPT_SEQUENCE
    AS SELECT * FROM DEPT WHERE 1 <> 1;
SELECT * FROM DEPT_SEQUENCE;


-- 13-28 시퀀스 생성
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 10
    START WITH 10
    MAXVALUE 90
    MINVALUE 0
    NOCYCLE
    CACHE 2;

-- 13-29 생성한 시퀀스 확인
SELECT * FROM USER_SEQUENCES;

-- 13-30 시퀀스에서 생성한 순번을 사용한 insert문
INSERT INTO DEPT_SEQUENCE VALUES(SEQ_DEPT_SEQUENCE.nextval, 'DATABASE', 'SEOUL');
SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

-- 13-31 가장 마지막으로 생성된 시퀀스 확인
SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;

-- 13-32 시퀀스에서 생성한 순번을 반복사용한 insert문
INSERT INTO DEPT_SEQUENCE VALUES(SEQ_DEPT_SEQUENCE.nextval, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_SEQUENCE VALUES(SEQ_DEPT_SEQUENCE.nextval, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_SEQUENCE VALUES(SEQ_DEPT_SEQUENCE.nextval, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_SEQUENCE VALUES(SEQ_DEPT_SEQUENCE.nextval, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_SEQUENCE VALUES(SEQ_DEPT_SEQUENCE.nextval, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_SEQUENCE VALUES(SEQ_DEPT_SEQUENCE.nextval, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_SEQUENCE VALUES(SEQ_DEPT_SEQUENCE.nextval, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_SEQUENCE VALUES(SEQ_DEPT_SEQUENCE.nextval, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_SEQUENCE VALUES(SEQ_DEPT_SEQUENCE.nextval, 'DATABASE', 'SEOUL');
SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;
 

-- 활용문제
-- 문제1
-- 1) EMP테이블과 같은 열과 행 구조와 데이터를 저장하는 테이블 생성
CREATE TABLE EMPIDX AS SELECT * FROM EMP;
-- 2) 생성한 테이블의 EMPNO열에 인덱스를 생성
CREATE INDEX IDX_EMPIDX_EMPNO ON EMPIDX(EMPNO);
-- 3) 인덱스가 잘 생성 되었는지 적절한 데이터 사전 뷰로 확인
SELECT * FROM USER_INDEXES;

-- 문제2 1번에서 생성한 테이블의 데이터 중 급여가 1500 초과인 사원만 출력하는 뷰를 생성해보세요. 이름이 같은 뷰가 이미 있다면 새로운 내용으로 바꿀 수 있어야합니다. 뷰는 사원번호, 이름, 직책, 부서번호, 급여, 추가수당 열로 구성되며, 추가수당 열은 추가 수당 유무에 따라 O,X 로 출력됩니다.
CREATE OR REPLACE VIEW EMPIDX_OVER15K
AS (SELECT 
        EMPNO, ENAME, JOB, DEPTNO, SAL, NVL2(COMM, 'O', 'X') COMM
    FROM EMP WHERE SAL > 1500
    );

SELECT * FROM EMPIDX_OVER15K;

-- 문제3
-- 1) DEPT 테이블과 같은 열과 행 구성인 테이블을 작성
CREATE TABLE DEPTSEQ AS SELECT * FROM DEPT;
-- 2) 생성한 DEPTSEQ 테이블의 DEPTNO열에 사용할 시퀀스를 생성
CREATE SEQUENCE DEPTSEQ_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE
    NOCACHE;
-- 3) DEPTSEQ 시퀀스를 사용하여 부서 3개를 추가
INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
    VALUES(DEPTSEQ_SEQ.nextval, 'DATABASE', 'SEOUL');
INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
    VALUES(DEPTSEQ_SEQ.nextval, 'WEB', 'BUSAN');
INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
    VALUES(DEPTSEQ_SEQ.nextval, 'MOBILE', 'ILSAN');

SELECT * FROM DEPTSEQ;