-- 10-1 테이블 복사하기
CREATE TABLE DEPT_TEMP AS SELECT * FROM DEPT;

-- 10-3 테이블에 데이터 추가하기
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES(50, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_TEMP VALUES(50, 'DATABASE', 'SEOUL');

-- Null 명시적 입력(아래 세 가지 방법 모두 가능)
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES(70, 'WEB', NULL);
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES(80, 'MOBILE', '');
INSERT INTO DEPT_TEMP (DEPTNO, LOC) VALUES(90, 'INCHEON');
-- pk 인 경우에는 null 불가 -> 에러발생

-- 테이블에 날짜 데이터 입력하기(YYYY/MM/DD 혹은 YYYY-MM-DD)
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES(9999, '홍길동', 'PRESIDENT', NULL, '2001/01/01', 5000, 1000, 10);
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES(1111, '성춘향', 'MANAGER', 9999, '2001-01-05', 4000, NULL, 20);
-- 사용하는 기본 언어에 따라 날짜 표기 방식이 다를 수 있으므로 TO_DATE 함수 사용 권장
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES(2111, '이순신', 'MANAGER', 9999, TO_DATE('07/01/2001', 'DD/MM/YYYY'), 4000, NULL, 20);
-- SYSDATE로 오늘 날짜 입력
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES(3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);



-- 10-14 서브쿼리로 한 번에 여러 데이터 추가
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND s.GRADE = 1;

SELECT * FROM EMP_TEMP;
SELECT * FROM DEPT_TEMP;


CREATE TABLE DEPT_TEMP2 AS SELECT * FROM DEPT;
-- 10-16 update
UPDATE DEPT_TEMP2 SET LOC = 'SEOUL';
-- 데이터 일부 수정
UPDATE DEPT_TEMP2 SET DNAME = 'DATABASE',
                        LOC = 'SEOUL'
                        WHERE DEPTNO = 40;

-- 수정한 내용 되돌릴 때
ROLLBACK;

-- 서브쿼리로 한 번에 데이터 수정하기
UPDATE DEPT_TEMP2
SET (DNAME, LOC) = (SELECT DNAME, LOC
                    FROM DEPT
                    WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;


-- DELETE
CREATE TABLE EMP_TEMP2 AS SELECT * FROM EMP;
-- 10-23 where로 일부만 삭제
DELETE FROM EMP_TEMP2 WHERE JOB = 'MANAGER';


-- 10-24 서브쿼리로 여러 개 삭제
DELETE FROM EMP_TEMP2 
WHERE EMPNO IN (SELECT E.EMPNO
                FROM EMP_TEMP2 E, SALGRADE S
                WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                    AND S.GRADE = 3
                    AND DEPTNO = 30);


DELETE FROM EMP_TEMP2; 
SELECT * FROM EMP_TEMP2;

-- 활용 문제
CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;
SELECT * FROM CHAP10HW_DEPT;
SELECT * FROM CHAP10HW_EMP;
SELECT * FROM CHAP10HW_SALGRADE;

-- 문제 1. DEPT 테이블에 50, 60, 70, 80번 부서 등록
INSERT INTO CHAP10HW_DEPT VALUES(50, 'ORACLE', 'BUSAN');
INSERT INTO CHAP10HW_DEPT VALUES(60, 'SQL', 'ILSAN');
INSERT INTO CHAP10HW_DEPT VALUES(70, 'SELECT', 'INCHEON');
INSERT INTO CHAP10HW_DEPT VALUES(80, 'DML', 'BUNDANG');


-- 문제 2. EMP에 8명의 사원 정보를 등록
INSERT INTO CHAP10HW_EMP 
        VALUES(7201, 'TEST_USER1', 'MANAGER', '7788', '2016/01/02', 4500, NULL, 50);
INSERT INTO CHAP10HW_EMP 
        VALUES(7202, 'TEST_USER2', 'CLERK', '7201', '2016/02/21', 1800, NULL, 50);
INSERT INTO CHAP10HW_EMP 
        VALUES(7203, 'TEST_USER3', 'ANALYST', '7201', '2016/04/11', 3400, NULL, 60);
INSERT INTO CHAP10HW_EMP 
        VALUES(7204, 'TEST_USER4', 'SALESMAN', '7201', '2016/05/31', 2700, 300, 60);
INSERT INTO CHAP10HW_EMP 
        VALUES(7205, 'TEST_USER5', 'CLERK', '7201', '2016/07/20', 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP 
        VALUES(7206, 'TEST_USER6', 'CLERK', '7201', '2016/09/08', 2600, NULL, 70);
INSERT INTO CHAP10HW_EMP 
        VALUES(7207, 'TEST_USER7', 'LECTURER', '7201', '2016/10/28', 2300, NULL, 80);
INSERT INTO CHAP10HW_EMP 
        VALUES(7208, 'TEST_USER8', 'STUDENT', '7201', '2018/03/09', 1200, NULL, 80);

-- 문제 3. EMP에 속한 사원 중 50번 부서에서 근무하는 사원의 평균 급여보다 많이 받는 사원을 70번으로 이동
UPDATE CHAP10HW_EMP SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL) 
                FROM CHAP10HW_EMP 
                WHERE DEPTNO = 50);

SELECT * FROM CHAP10HW_EMP order by deptno;

-- 문제 4. EMP에 속한 사원 중 입사일이 가장 빠른 60번 부서 사원보다 늦게 입사한 사원의 급여를 10% 인상하고 80 번 부서로 이동
UPDATE CHAP10HW_EMP SET SAL = SAL * 1.1,
                        DEPTNO = 80
WHERE HIREDATE > (SELECT MIN(HIREDATE)
                    FROM CHAP10HW_EMP
                    WHERE DEPTNO = 60);
SELECT * FROM CHAP10HW_EMP order by deptno;

-- 문제 5. EMP에 속한 사원 중 급여 등급이 5인 사원 삭제
DELETE FROM CHAP10HW_EMP 
WHERE EMPNO IN (SELECT E.EMPNO
                FROM CHAP10HW_EMP E, SALGRADE S
                WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                AND S.GRADE = 5);