-- 9-3 서브쿼리로 JONES의 급여보다 높은 급여를 받는 사원 정보 출력
SELECT * FROM EMP
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME = 'JONES');

-- 9-5 단일행 서브쿼리와 함수
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
    AND E.DEPTNO  = 20
    AND E.SAL > (SELECT AVG(SAL) FROM EMP);
    
-- 9-7 실행 결과가 여러 개인 다중행 서브쿼리
SELECT * FROM EMP
WHERE SAL IN (SELECT MAX(SAL) 
                FROM EMP 
                GROUP BY DEPTNO);

-- 9-19 인라인 뷰 : from 절에 사용하는 서브 쿼리
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
FROM 
    (SELECT * FROM EMP WHERE DEPTNO=10) E10,
    (SELECT * FROM DEPT) D
WHERE E10.DEPTNO = D.DEPTNO;

SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
FROM 
    (SELECT * FROM EMP WHERE DEPTNO=10) E10 JOIN
    (SELECT * FROM DEPT) D
ON E10.DEPTNO = D.DEPTNO;

-- Structured Query Language 


-- 9-20 with 절: 사용하는 서브쿼리를 먼저 지정
WITH
E10 AS (SELECT * FROM EMP WHERE DEPTNO=10),
D AS (SELECT * FROM DEPT)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
FROM 
     E10,
     D
WHERE E10.DEPTNO = D.DEPTNO;

-- 9-21 select 절에 사용하는 서브쿼리
SELECT EMPNO, ENAME, JOB, SAL,
    (SELECT GRADE FROM SALGRADE WHERE E.SAL BETWEEN LOSAL AND HISAL) SALGRADE,
    DEPTNO,
    (SELECT DNAME FROM DEPT WHERE E.DEPTNO = DEPTNO) AS DNAME
FROM EMP E;

-- 문제 1
SELECT 
    e.JOB,
    e.EMPNO,
    e.ENAME,
    e.SAL,
    d.DEPTNO,
    d.DNAME
FROM EMP e, DEPT d
WHERE d.DEPTNO = e.DEPTNO
    AND e.JOB = (SELECT job
                FROM EMP
                WHERE ename = 'ALLEN');

-- 문제 2
SELECT 
    e.EMPNO,
    e.ENAME,
    d.DNAME,
    e.HIREDATE,
    d.LOC,
    e.SAL,
    s.GRADE
FROM EMP e JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
JOIN SALGRADE s ON e.SAL BETWEEN s.LOSAL AND s.HISAL
WHERE e.SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY e.SAL desc, e.EMPNO asc;

-- 문제 3
SELECT
    e.EMPNO,
    e.ENAME,
    e.JOB,
    d.DEPTNO,
    d.DNAME,
    d.LOC
FROM EMP e, DEPT d
WHERE e.DEPTNO = 10
    AND e.DEPTNO = d.DEPTNO
    AND e.JOB not IN (SELECT JOB FROM EMP WHERE DEPTNO = 30);

-- 문제 4
SELECT 
    e.EMPNO,
    e.ENAME,
    e.SAL,
    s.GRADE
FROM EMP e, SALGRADE s
WHERE e.SAL BETWEEN s.LOSAL AND s.HISAL
    AND e.SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN')
ORDER BY e.EMPNO;


-- 페이징
SELECT
    EMPNO, ENAME, ROWNUM
FROM EMP;

SELECT
    EMPNO, ENAME, ROWNUM
FROM EMP
ORDER BY HIREDATE DESC;

SELECT A.EMPNO, A.ENAME, ROWNUM 
FROM(
    SELECT
        EMPNO, ENAME
    FROM EMP
    ORDER BY HIREDATE DESC
) A;


SELECT * 
FROM (
    SELECT A.EMPNO, A.ENAME, ROWNUM RM
    FROM(
        SELECT
            EMPNO, ENAME
        FROM EMP
        ORDER BY HIREDATE DESC
    ) A
) B
WHERE B.RM BETWEEN 11 AND 20;